"""
generate_synthetic.py — Create fake sensor data for training and testing
=========================================================================

WHY THIS FILE EXISTS:
    We don't have a real paper-clip machine, so we generate realistic synthetic
    data.  This lets us:
    - Train the autoencoder on "normal" data
    - Test it with known anomalies to verify it works

HOW IT WORKS:
    For each tag, we define a centre value and a noise range.  Normal samples
    are generated by adding small random noise to the centre.  Anomalous samples
    have a few tags pushed well outside their normal range.

OUTPUT:
    data/normal_train.csv   — 5000 "normal" samples for training
    data/test_mixed.csv     — 1000 samples:  ~90% normal + ~10% anomalous
                              (with an "is_anomaly" label column for evaluation)
"""

import os
import numpy as np
import csv

# ---------------------------------------------------------------------------
# Tag definitions: (name, centre_value, noise_half_width)
#
# Normal samples: centre ± noise_half_width (uniform random)
# These ranges are chosen to be plausible for a paper-clip machine.
# ---------------------------------------------------------------------------
TAG_SPECS = [
    # name                  centre  noise
    ("wire_feed_speed",     10.0,   2.0),    # m/min,  range ~[8, 12]
    ("wire_tension",        22.5,   7.5),    # N,      range ~[15, 30]
    ("motor_current_feed",  2.25,   0.75),   # A,      range ~[1.5, 3.0]
    ("motor_current_bend",  3.25,   1.25),   # A,      range ~[2.0, 4.5]
    ("bend_angle",          180.0,  2.0),    # deg,    range ~[178, 182]
    ("cycle_time",          200.0,  20.0),   # ms,     range ~[180, 220]
    ("vibration_rms",       1.75,   1.25),   # mm/s,   range ~[0.5, 3.0]
    ("cut_force",           55.0,   15.0),   # N,      range ~[40, 70]
    ("temperature_motor",   47.5,   17.5),   # °C,     range ~[30, 65]
    ("reject_count_per_min", 1.0,   1.0),    # count,  range ~[0, 2]
]

TAG_NAMES = [name for name, _, _ in TAG_SPECS]
CENTRES   = np.array([c for _, c, _ in TAG_SPECS])
NOISES    = np.array([n for _, _, n in TAG_SPECS])


def generate_normal_samples(n: int, seed: int = 42) -> np.ndarray:
    """
    Generate n samples of normal sensor data.

    Each tag value = centre + uniform_random(-noise, +noise).

    Returns
    -------
    np.ndarray, shape (n, 10)
    """
    rng = np.random.default_rng(seed)
    # rng.uniform produces random numbers in [low, high)
    # We generate an (n, 10) array where each column is one tag.
    samples = CENTRES + rng.uniform(-NOISES, NOISES, size=(n, len(TAG_SPECS)))
    return samples


def inject_anomalies(samples: np.ndarray, fraction: float = 0.10,
                     seed: int = 99) -> tuple[np.ndarray, np.ndarray]:
    """
    Take an array of normal samples and randomly corrupt some of them.

    For each anomalous sample, we pick 1–3 random tags and push them far
    outside the normal range (3–5× the noise width).

    Parameters
    ----------
    samples : np.ndarray, shape (n, 10)
    fraction : float
        Proportion of samples to make anomalous (default 10 %).
    seed : int

    Returns
    -------
    corrupted : np.ndarray, shape (n, 10)
        The data with some samples modified.
    labels : np.ndarray, shape (n,)
        0 = normal, 1 = anomaly.
    """
    rng = np.random.default_rng(seed)
    corrupted = samples.copy()
    n = len(samples)
    labels = np.zeros(n, dtype=int)

    n_anomalies = int(n * fraction)
    anomaly_indices = rng.choice(n, size=n_anomalies, replace=False)

    for idx in anomaly_indices:
        labels[idx] = 1
        # Pick 1–3 random tags to corrupt
        n_tags_to_corrupt = rng.integers(1, 4)  # 1, 2, or 3
        tag_indices = rng.choice(len(TAG_SPECS), size=n_tags_to_corrupt, replace=False)

        for tag_idx in tag_indices:
            # Push the value 3–5× outside the normal noise range
            direction = rng.choice([-1, 1])
            magnitude = rng.uniform(3.0, 5.0) * NOISES[tag_idx]
            corrupted[idx, tag_idx] = CENTRES[tag_idx] + direction * magnitude

    return corrupted, labels


def save_csv(filepath: str, data: np.ndarray, headers: list[str]) -> None:
    """Save a numpy array to CSV with headers."""
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(headers)
        for row in data:
            writer.writerow([round(float(v), 4) for v in row])
    print(f"  Saved {len(data)} rows → {filepath}")


def main():
    print("Generating synthetic paper-clip sensor data ...\n")

    # --- 1. Training data (normal only) ---------------------------------------
    # WHY no anomalies in training data: the autoencoder learns what "normal"
    # looks like.  If we included anomalies, it would learn to reconstruct them
    # too, defeating the purpose.
    print("1) Normal training data (5000 samples):")
    normal_train = generate_normal_samples(5000, seed=42)

    # We save individual samples (not windowed).  train.py will handle windowing.
    save_csv("data/normal_train.csv", normal_train, TAG_NAMES)

    # --- 2. Test data (mixed: normal + anomalous) -----------------------------
    print("\n2) Test data (1000 samples, ~10% anomalous):")
    normal_test = generate_normal_samples(1000, seed=123)
    test_mixed, labels = inject_anomalies(normal_test, fraction=0.10, seed=99)

    # Add the label column so we can evaluate accuracy later
    test_with_labels = np.column_stack([test_mixed, labels])
    headers_with_label = TAG_NAMES + ["is_anomaly"]
    save_csv("data/test_mixed.csv", test_with_labels, headers_with_label)

    n_anomalies = int(labels.sum())
    print(f"\n  → {n_anomalies} anomalous samples, {len(labels) - n_anomalies} normal samples")
    print("\nDone!  Data saved in data/ directory.")


if __name__ == "__main__":
    main()
