"""
train.py — Train the autoencoder on normal data
=================================================

WHY THIS FILE EXISTS:
    Before the detector can identify anomalies, it needs to learn what "normal"
    looks like.  This script:

    1.  Reads normal_train.csv (generated by generate_synthetic.py)
    2.  Simulates windowing: groups every 30 consecutive rows and averages them.
    3.  Fits a MinMaxScaler on the averaged data (so every feature is in [0, 1]).
    4.  Trains the autoencoder to reconstruct these normal samples.
    5.  Computes the anomaly threshold (mean + 3σ of training reconstruction errors).
    6.  Saves three artefacts to the models/ directory:
            - autoencoder.tflite  (model converted to TFLite flat-buffer format)
            - scaler.pkl          (fitted scaler)
            - threshold.json      (threshold value)

HOW TRAINING WORKS (intuition):
    We show the network thousands of "normal" examples and ask it:
    "compress this to 16 numbers, then rebuild the original 10."
    Each time, we measure how wrong the reconstruction is (the loss = MSE).
    The optimizer nudges the network weights to make the loss smaller.
    After many passes (epochs), the network becomes very good at reconstructing
    normal data — but it has never seen anomalies, so it will fail on those.

FRAMEWORK — TensorFlow / Keras + TFLite conversion:
    Training uses full TensorFlow on a development machine (x86_64).
    After training, the Keras model is converted to a compact .tflite file.
    Only the .tflite file (+ scaler + threshold) is deployed to the edge device.
    The edge device runs inference with the lightweight tflite-runtime package,
    which can also delegate computation to the NXP NPU when enabled.

USAGE:
    cd anomaly_detection
    python training/train.py
"""

import json
import os
import pickle
import sys

import numpy as np
import yaml

BASE_DIR = os.path.join(os.path.dirname(__file__), "..")

# Add src/ to the Python path so we can import our model module
sys.path.insert(0, os.path.join(BASE_DIR, "src"))
from model import build_keras_model, convert_to_tflite  # noqa: E402


def load_csv(filepath: str) -> np.ndarray:
    """Load a CSV file (skipping the header) into a numpy array."""
    return np.loadtxt(filepath, delimiter=",", skiprows=1, dtype=np.float32)


def simulate_windowing(data: np.ndarray, window_size: int) -> np.ndarray:
    """
    Group consecutive rows into non-overlapping windows and average each window.

    For example, if data has 5000 rows and window_size=30:
        → 5000 // 30 = 166 windows
        → output shape: (166, 10)

    This mirrors what preprocessing.py does at runtime: the detector receives
    one sample per second, buffers 30, then averages them.  We replicate that
    here so the model trains on the same kind of input it will see in production.
    """
    n_windows = len(data) // window_size
    trimmed = data[: n_windows * window_size]
    windows = trimmed.reshape(n_windows, window_size, -1)
    return windows.mean(axis=1)  # shape: (n_windows, n_tags)


def main():
    # --- Load config ----------------------------------------------------------
    config_path = os.path.join(BASE_DIR, "config.yaml")
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    model_cfg = config["model"]
    train_cfg = config["training"]
    prep_cfg = config["preprocessing"]

    print("=" * 60)
    print("  TRAINING THE AUTOENCODER  (TensorFlow / Keras)")
    print("=" * 60)

    # --- Step 1: Load and window the data -------------------------------------
    print("\n[1/5] Loading training data ...")
    raw_data = load_csv(os.path.join(BASE_DIR, "data", "normal_train.csv"))
    print(f"  Raw samples: {raw_data.shape[0]} rows × {raw_data.shape[1]} tags")

    windowed = simulate_windowing(raw_data, prep_cfg["window_size"])
    print(f"  After windowing (size={prep_cfg['window_size']}): {windowed.shape[0]} averaged samples")

    # --- Step 2: Fit and apply the scaler -------------------------------------
    print("\n[2/5] Fitting MinMaxScaler ...")
    # WHY MinMaxScaler: transforms each feature to [0, 1], which matches the
    # Sigmoid output of the autoencoder and prevents scale imbalance between tags.
    from sklearn.preprocessing import MinMaxScaler
    scaler = MinMaxScaler()
    scaled_data = scaler.fit_transform(windowed).astype(np.float32)
    print(f"  Scaler fitted.  Ranges learned for {scaled_data.shape[1]} features.")

    # --- Step 3: Build the Keras model ----------------------------------------
    print("\n[3/5] Building autoencoder (Keras) ...")
    model = build_keras_model(
        input_size=model_cfg["input_size"],
        hidden_size=model_cfg["hidden_size"],
        bottleneck_size=model_cfg["bottleneck_size"],
    )
    print(f"  Architecture: {model_cfg['input_size']} → {model_cfg['hidden_size']} "
          f"→ {model_cfg['bottleneck_size']} → {model_cfg['hidden_size']} → {model_cfg['input_size']}")

    # Compile: specify the loss function and optimizer.
    # MSE is used as both the training loss and the anomaly score at inference.
    # Adam is a popular adaptive optimizer that works well out of the box.
    import tensorflow as tf
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=train_cfg["learning_rate"]),
        loss="mse",
    )

    # --- Step 4: Training -----------------------------------------------------
    print(f"\n[4/5] Training for {train_cfg['epochs']} epochs "
          f"(batch_size={train_cfg['batch_size']}, lr={train_cfg['learning_rate']}) ...")

    # Keras model.fit() replaces the manual training loop.
    # autoencoder: input == target (self-supervised reconstruction task).
    model.fit(
        x=scaled_data,
        y=scaled_data,            # target = input (autoencoder)
        epochs=train_cfg["epochs"],
        batch_size=train_cfg["batch_size"],
        shuffle=True,
        verbose=0,                # suppress per-step logs; we print epochs below
        callbacks=[
            tf.keras.callbacks.LambdaCallback(
                on_epoch_end=lambda epoch, logs: (
                    print(f"  Epoch {epoch+1:3d}/{train_cfg['epochs']}  —  "
                          f"avg loss: {logs['loss']:.6f}")
                    if (epoch + 1) % 10 == 0 or epoch == 0 else None
                )
            )
        ],
    )

    # --- Step 5: Compute threshold and save everything ------------------------
    print("\n[5/5] Computing anomaly threshold ...")

    # Reconstruct all training samples using the trained model (NumPy, no grad)
    all_reconstructed = model.predict(scaled_data, verbose=0)

    # Per-sample MSE: average of squared differences over the feature dimension
    mse_per_sample = np.mean((scaled_data - all_reconstructed) ** 2, axis=1)

    mse_mean = float(mse_per_sample.mean())
    mse_std = float(mse_per_sample.std())
    sigma = train_cfg["threshold_sigma"]
    threshold = mse_mean + sigma * mse_std

    print(f"  Training MSE  — mean: {mse_mean:.6f}, std: {mse_std:.6f}")
    print(f"  Threshold (mean + {sigma}σ): {threshold:.6f}")

    # --- Save artefacts -------------------------------------------------------
    models_dir = os.path.join(BASE_DIR, "models")
    os.makedirs(models_dir, exist_ok=True)

    # Convert to TFLite and save the flat-buffer file.
    # The .tflite file embeds both the graph and the trained weights — it is the
    # only model artefact needed on the edge device.
    tflite_path = os.path.join(models_dir, "autoencoder.tflite")
    convert_to_tflite(model, tflite_path)
    print(f"\n  ✅ TFLite model saved → {tflite_path}")

    # Save scaler (unchanged — sklearn pickle is architecture-independent)
    scaler_path = os.path.join(models_dir, "scaler.pkl")
    with open(scaler_path, "wb") as f:
        pickle.dump(scaler, f)
    print(f"  ✅ Scaler saved       → {scaler_path}")

    # Save threshold
    threshold_path = os.path.join(models_dir, "threshold.json")
    with open(threshold_path, "w") as f:
        json.dump({"threshold": threshold, "mean": mse_mean, "std": mse_std, "sigma": sigma}, f, indent=2)
    print(f"  ✅ Threshold saved    → {threshold_path}")

    print("\n" + "=" * 60)
    print("  TRAINING COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
